name: .NET CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore backend/Appointments.sln

    - name: Build
      run: dotnet build backend/Appointments.sln --no-restore --configuration Release

    - name: Run tests
      run: dotnet test backend/Appointments.sln --no-build --verbosity normal
